apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    chart: secrets-store-csi-driver
    helm:
      parameters:
      - name: syncSecret.enabled
        value: "true"
      values: |
        linux:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                    - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
            
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    targetRevision: 1.3.4
