apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: keda
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.11.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
