apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  destination:
    name: cluster-latest
    namespace: kyverno
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.0.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
