apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-provider-aws
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    chart: secrets-store-csi-driver-provider-aws
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.4
