version: "3"
services:
  main:
    build: .
    ports:
      - "8088:5000"
    # command: ["tail", "-f", "/dev/null"]
    environment:
      - FLASK_ENV=development
    volumes:
      - ~/.aws:/root/.aws
      - .:/usr/src/app/
      - logvolume01:/var/log
volumes:
  logvolume01: {}
